### ISSUE TITLE
Shading採点

### ISSUE THREAD

**Issue by m5261163** [takamiyuto/CG_exercises#12]
TAの曾我です。コードの内容を確認しましたが、基本的な部分は問題なさそうでした。しかし、Blinnモデルのハーフベクトルの計算がif文の中に入っており、一度Blinnに切り替えないと計算がされないのでその後のBurleyモデルの計算で値が不定になる可能性があります。実行してみても問題はなかったのですが一応if文の外で計算をした方が良いと思います。
https://github.com/takamiyuto/CG_exercises/blob/2eff8d3330b12188d91fd83bea85878ce265a0e2/ex3/shading.c#L151
https://github.com/takamiyuto/CG_exercises/blob/2eff8d3330b12188d91fd83bea85878ce265a0e2/ex3/shading.c#L162-L170
また、ライトの切り替えがOpenGLの方にしか適用されていないので`g_num_lights`を変更するなどして、独自実装の方でも反映させるようにしてください。

**Comment by takamiyuto** [comment]
上の修正点を直し、コミットしましたので確認をお願いします。

**Comment by m5261163** [comment]
返信遅れまして大変申し訳ございません。こちら修正確認しましたのでこのまま採点させていただきます。お疲れさまでした。
