### ISSUE TITLE
RayTracing採点

### ISSUE THREAD

**Issue by m5261163** [takamiyuto/CG_exercises#13]
TAの曾我です。コードの内容を確認しましたが、光源計算のSpecular成分がうまく計算できていないようです。視点ベクトルの計算ですが、今回は前回の演習と違いView空間で計算しているわけではないので視点ベクトルはカメラの座標を使って計算する必要があります。
https://github.com/takamiyuto/CG_exercises/blob/2eff8d3330b12188d91fd83bea85878ce265a0e2/ex4/RayTrace.c#L196-L198

**Comment by takamiyuto** [comment]
修正して、コミットしましたので確認をお願いします

**Comment by m5261163** [comment]
返信遅れまして大変申し訳ございません。こちら確認しましたのでこのまま採点させていただきます。お疲れさまでした。
