### ISSUE TITLE
Transformations採点

### ISSUE THREAD

**Issue by m5261163** [takamiyuto/CG_exercises#9]
TAの曾我です。コードの内容を確認しました。全体的には問題なさそうですが、プロジェクション変換系の関数が自作のものに置き換えられていないようでしたのでそれらを置き換えるようにしてください。キーボードで切り替えられるようにするとなお良いと思います。
https://github.com/takamiyuto/CG_exercises/blob/c1e76baaaa2e3e51cb0172a3ce2a4a2203bbcee0/ex2/platonic.c#L207-L219

**Comment by takamiyuto** [comment]
gluPerspectiveとglOrthoをmyPerspectiveとmyOrthoに変更するコミットをしました。

**Comment by m5261163** [comment]
返信遅れまして大変申し訳ございません。修正確認しましたのでこちらで採点させていただきます。お疲れさまでした。
